Allow deletion of disappeared groups
appuio/group-sync-operator pull request #2
Opened 2021-11-23 16:05 UTC by bastjan

This PR allows deletion of disappeared groups.

It does so by checking for the `group-sync-operator.redhat-cop.io/sync-provider` label and deleteing groups which sync timestamp was not updated.

A `static` provider was added for easier testing.

2021-11-23 16:06 UTC, bastjan commented on controllers/groupsync_controller.go
> +					continue
On second thought maybe we should create a set of seen groups in the steps before? Would make the code a tad more complicated but could be safer.

2021-11-23 17:16 UTC, glrf requested changes
Looks pretty good. I really like the tests :)

However I don't understand why you are using timestamps. Maybe I'm missing something. My approach would have been

* Get all OpenShift groups with the provider label
* Get the list of groups from the provider
* Make diff of these two lists and remove all that are in the former but not in the latter

That would be more resilient and IMO not more complicated.

2021-11-23 17:16 UTC, glrf commented on controllers/groupsync_controller.go
> +					continue
If you mean by that to the groups with the correct `providerLabel` before and compare them the `groups` returned by the `groupSyncer` and remove all that are not present, then yes that sound more resilient and I would prefer that.

I'm not quite sure why you are working with the timestamp at all. You have the list of groups that have been returned by the provider and can compare it to the existing groups.

2021-11-23 17:16 UTC, glrf commented on controllers/groupsync_controller.go
> +		providerLabel := fmt.Sprintf("%s_%s_%s", instance.Namespace, instance.Name, groupSyncer.GetProviderName())
I get why you're doing that, but that's strictly speaking a breaking change. I have no idea if anyone depends on that label. If we want to upstream this sometime, I would be cautious and use a new label.

2021-11-23 17:16 UTC, glrf commented on controllers/groupsync_controller.go
> +		syncTimestampAnnotation := clock.Now().Format(time.RFC3339Nano)
Technically their `ISO8601` is not RFC3339. But their implementation is utterly broken so fixing that is fine I guess :sweat_smile:

2021-11-23 17:16 UTC, glrf commented on controllers/groupsync_controller_test.go
> +	It("It should sync groups from the provider", func() {
For Ginkgo tests you don't need to add the `It` or `By` as in the output that should be added already.  But that's a very minor nitpick :)
```suggestion
	It("should sync groups from the provider", func() {
```

2021-11-23 18:20 UTC, ccremer approved these changes
I agree with @glrf 's suggestions

2021-11-23 18:20 UTC, ccremer commented on README.md
> +
It would have been better to make the static provider into its own PR, but no hard feelings here.

2021-11-24 07:52 UTC, bastjan commented on README.md
> +
I used the static provider for the unit tests too. that's why it's an all-in-one PR 😅

2021-11-24 07:53 UTC, bastjan commented on controllers/groupsync_controller.go
> +		providerLabel := fmt.Sprintf("%s_%s_%s", instance.Namespace, instance.Name, groupSyncer.GetProviderName())
You're right. I'll add an additional label instead.

2021-11-24 09:20 UTC, glrf approved these changes
LGTM :rocket: 

Only some very minor nitpicks.

2021-11-24 09:20 UTC, glrf commented on controllers/groupsync_controller.go
> +		syncTimestampAnnotation := clock.Now().Format(time.RFC3339)
As you now don't need the timestamp to be the same for all groups, I would personally move that to down to where it's used and not add another variable.

2021-11-24 09:20 UTC, glrf commented on controllers/groupsync_controller.go
> +					log.Error(err, "Failed to Create or Update OpenShift Group")
Missed that last time. You're not creating or updating anything :sweat_smile:

2021-11-24 09:32 UTC, bastjan commented on controllers/groupsync_controller.go
> +					log.Error(err, "Failed to Create or Update OpenShift Group")
🖨🍝

2021-11-24 10:31 UTC, merged